seed: 42
device: cuda

paths:
  train_manifest: /data1/zhaoyd/heightnet_frame_manifests/400cm_slantside_stage1_max3_1fps_extracted/train_manifest.csv
  val_manifest: /data1/zhaoyd/heightnet_frame_manifests/400cm_slantside_stage1_max3_1fps_extracted/val_manifest.csv
  test_manifest: /data1/zhaoyd/heightnet_frame_manifests/400cm_slantside_stage1_max3_1fps_extracted/test_manifest.csv
  train_video_root: ''
  val_video_root: ''
  test_video_root: ''
  bg_depth_root: /data1/zhaoyd/2503_test_bg_depthmap
  output_dir: /data1/zhaoyd/heightnet_repro/runs/by_camera/400cm_slantside_frame1fps_max3_extracted_vitl_vit_mapcons_50ep

train:
  epochs: 50
  batch_size: 16
  num_workers: 16
  lr: 0.0001
  weight_decay: 0.0001
  grad_clip_norm: 1.0
  use_amp: true
  use_tensorboard: true
  log_interval: 20
  tb_num_images: 4

loss:
  lambda_rmse: 1.0
  lambda_rank: 1.0
  lambda_cons: 0.1
  eps: 1.0e-06
  min_valid_pixels: 64
  min_valid_ratio: 0.002
  pairwise_json: /data1/zhaoyd/heightnet_repro/data/pairwise_rank/all_pairs.json
  consistency_mode: map

data:
  image_size: [352, 704]
  normalize_rgb: true
  use_pair_consistency: true

model:
  name: heightnet_tiny
  base_channels: 32
  comparator_channels: 16
  comparator_type: vit
  comparator_layers: 2
  comparator_num_heads: 4
  comparator_patch_size: 16

eval:
  save_visualizations: true
  vis_limit: 20
  video_feature_frames: 30
  frames_per_person_eval: 10
  frame_eval_seed: 42
  save_train_gallery: true

runtime_seg:
  enabled: true
  model_path: /data1/zhaoyd/models/yolov8n-seg.pt
  conf: 0.25
  iou: 0.7
  imgsz: 640
  strict_native: true

runtime_depth:
  enabled: true
  depthanything_root: /data1/zhaoyd/Depth-Anything-V2
  encoder: vitl
  checkpoint: /data1/zhaoyd/models/depth_anything_v2_vitl.pth
  input_size: 518
  assume_inverse: false
